# CI settings for Travis-CI
# (Don't write hard tab in this file)
language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
    - npm install
script:
    - npm test
